import "@rainbow-me/rainbowkit/styles.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { DeployProvider } from "@/context/deploy";
import { Toaster } from "sonner";
import RootProvider from "@/context/root";
import Navbar from "@/components/nav";
import Footer from "@/components/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Hookstore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RootProvider>
          <Toaster richColors theme="dark" closeButton />
          <DeployProvider>
            <main className="min-h-screen flex flex-col">
              <Navbar />
              {children}
              <div className="flex grow"></div>
              <Footer />
            </main>
          </DeployProvider>
        </RootProvider>
      </body>
    </html>
  );
}
